# ============================== Filebeat inputs ===============================
- type: log
  # 多行合并
  multiline.pattern: '^[[:space:]]+(at|\.{3})[[:space:]]+\b|^Caused by:'
  multiline.negate: false
  multiline.match: after
  enabled: true
  paths:
      - /var/log/messages

  scan_frequency: 10s
  fields_under_root: true
  
  json.keys_under_root: true
  json.overwrite_keys: true
  json.add_error_key: true
  json.message_key: message

  fields:
      # 用于区分各个输入源作为索引名称、topic名称、redis键
      topic: test-messages
  tail_files: true
  close_inactive: 2h
  close_eof: false
  close_removed: true
  clean_removed: true
  close_renamed: false